# Generated by Django 2.0.3 on 2018-03-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20180328_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_isactive',
            field=models.BooleanField(default=False),
        ),
    ]
