# Generated by Django 2.0.3 on 2018-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20180329_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_isactive',
            field=models.BooleanField(),
        ),
    ]
