# Generated by Django 2.0.3 on 2018-03-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_user_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User1',
        ),
    ]
