# Generated by Django 2.0.3 on 2018-03-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_auto_20180330_1020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
